### ISSUE TITLE
Incorrect handling of arrays with gaps

### ISSUE THREAD

**Issue by KapitanOczywisty** [daniel-zahariev/json2php#12]
Function cannot handle gaps in arrays

```js
import json2php from "json2php";

console.log(json2php([1, , , , , 3]));
```
Results in:
```php
array(1, , , , , 3)
// Fatal error: Cannot use empty array elements in arrays in /in/KKbIJ on line 3
```
https://3v4l.org/KKbIJ

Best would be treat arrays like objects.

**Comment by daniel-zahariev** [comment]
Hi @KapitanOczywisty, the library isn't intended to handle gaps because they're not part of JSON specification.

**Comment by daniel-zahariev** [comment]
@KapitanOczywisty, `[1,,,2]` simply isn't valid JSON. You can [test it](https://jsonlint.com/) for yourself.
If you're unhappy due to the lack of errors or exceptions feel free to fork, modify and publish your upgraded library.

**Comment by KapitanOczywisty** [comment]
I know it's invalid, but You're providing JS object not JSON string as function argument.

And yes, I've already produced my own implementation, since I cannot afford script which results in invalid PHP without any warning and doesn't have any fail-safe for circular references.
