### ISSUE TITLE
Support short array syntax via pretty printing

### ISSUE THREAD

**Issue by ocean90** [daniel-zahariev/json2php#14]
Short array syntax was added to PHP in 5.4 and means you can use `[]` instead of `array()`.
Now that pretty print capability was added via 89082da469ef0ac2912174f4c539f0fad6732519 I'm wondering if we can extend that to also support something like `json2php.make({linebreak:'\n', indent:'\t', short: true})` which would export the data with the short array syntax.

What do you think?

**Comment by daniel-zahariev** [comment]
Hi @ocean90, sounds like a good idea.
Will add it in the next few days.

**Comment by daniel-zahariev** [comment]
Hi @ocean90 & @michalfelski,
I've added `shortArraySyntax` pretty print option in the version 0.0.7 of the package that is now published.
