### ISSUE TITLE
Improve usage documentation

### ISSUE THREAD

**Issue by BrodaNoel** [daniel-zahariev/json2php#8]
When you say:

```
json2php([1, 2, 3])
// => array(1, 2, 3) 
```

What is the meaning?
Probably you could say:

```
var foo = json2php([1, 2, 3])
// foo = 'array(1, 2, 3)'
```

Because, when you say `array(1, 2, 3)`, it sounds... weird... because it's not a string, but, if it's not a string, what is it?
json2php() function return the String that should be evaluated as a PHP script, right?

**Comment by daniel-zahariev** [comment]
Hi Broda,
yes, the function returns a string that is the PHP representation of the JavaScript object/array/string/number and this string can be evaluated as PHP code.
